git_user_email: 
git_private_key.private_key:
pivnet_token: 
credhub.server:
credhub_ca_cert.certificate:
credhub_client.username:
credhub_client.password:

opsman_admin.username:
opsman_admin.password:
decryption-passphrase:
opsman_target:
