---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfplatformrecovery/bbr-pcf-pipeline-tasks
    tag: final

inputs:
  - name: platform-automation-pipelines
    # Directory containing the bbr executable
  - name: bbr-release
  - name: config

params:
  ENV_FILE: env.yml

run:
  path: bash
  args:
    - -exc
    - |
      #!/usr/bin/env bash

      set -eu

      ## for BOSH_xxx
      om --env ./config/$ENV_FILE bosh-env > bosh-env.sh
      source bosh-env.sh

      mv ./bbr-release/*linux* ./bbr-release/bbr
      chmod +x ./bbr-release/bbr

      # Get bbr ssh credentials
      om --env ./config/$ENV_FILE curl -p /api/v0/deployed/director/credentials/bbr_ssh_credentials > bbr_ssh_credentials.json

      ## parse deployment
      jq -r '.[] | .value.private_key_pem' bbr_ssh_credentials.json > bbr_ssh_credentials

      ./bbr-release/bbr director --host "${BOSH_ENVIRONMENT}" \
        --username bbr \
        --private-key-path ./bbr_ssh_credentials \
        backup-cleanup

