---
platform: linux


inputs:
  - name: config
  - name: pipelines
  - name: bbr-release

outputs:
  - name: generated-backup

params:
  ENV_FILE: env.yml
  BBR_BACKUP_FILE: 

run:
  path: pipelines/tasks/bbr-backup-director-old.sh
