## https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/tree/master/tasks/bbr-backup-director
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfplatformrecovery/bbr-pcf-pipeline-tasks
    tag: final

inputs:
  - name: pipelines
    # Directory containing the bbr executable
  - name: bbr-release
  - name: config

outputs:
  # Contains `director-backup.tar` artifact created by `bbr director backup`
  - name: backup-artifact

params:
  ENV_FILE: env.yml
  FOUNDATION:
  BACKUP_FILE: director-backup_${current_date}.tar
  SSH_ENABLED: 
  SSH_HOST: 
  SSH_USERNAME: 
  SSH_PRIVATEE_KEY:


run:
  path: bash
  args:
    - -exc
    - |
      #!/usr/bin/env bash

      set -eu
      
      printf -- "$SSH_PRIVATEE_KEY" > ssh.key
      cat ssh.key
      chmod 600 ssh.key

      REMOTE_DIR="~/bbr-bakcup"

      ssh -i ssh.key -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} "mkdir -p $REMOTE_DIR"

      cat config/$ENV_FILE 
      
      scp -i ssh.key -o StrictHostKeyChecking=no config/$ENV_FILE ${SSH_USERNAME}@${SSH_HOST}:$REMOTE_DIR/env.yml

      scp -i ssh.key -o StrictHostKeyChecking=no -r pipelines/scripts/* ${SSH_USERNAME}@${SSH_HOST}:$REMOTE_DIR

      ssh -i ssh.key -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} "ls -al $REMOTE_DIR"

      ssh -i ssh.key -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} "chmod +x $REMOTE_DIR/*.sh"

      ssh -i ssh.key -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} "$REMOTE_DIR/setup-bbr-env.sh"

      ssh -i ssh.key -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} "$REMOTE_DIR/bbr-director-backup.sh"




