---
platform: linux


inputs:
  - name: state
  - name: platform-automation-pipelines


params:
  ENV_FILE: env.yml
  STATE_FILE: state.yml
  GOVC_DATACENTER:
  GOVC_INSECURE: 1
  GOVC_URL:
  GOVC_USERNAME:
  GOVC_PASSWORD:

run:
  path: platform-automation-pipelines/tasks/poweroff-vm.sh

