---
platform: linux

inputs:
- name: platform-automation-pipelines
- name: terraform-state
# contains YAML files with extension `.yml`.
# Each one of these files will have their values interpolated from credhub.
# For examples, run: `credhub interpolate --help`
# (minimum version >= 2.1.0 required)

# all params are required to be filled out
params:

  CREDHUB_CLIENT:
  CREDHUB_SECRET:
  CREDHUB_SERVER:
  # - Required
  # - Credentials to talk to credhub server

  CREDHUB_CA_CERT:
  # - Optional
  # - This is only necessary if your Concourse worker
  #   is not already configured to trust the CA used for Credhub.
  # - If more than one CA cert is required (ie the UAA),
  #   the CA certs can be concatenated together and separated by a newline.
  #   For example,
  #   CREDHUB_CA_CERT: |
  #     -----BEGIN CERTIFICATE-----
  #     ...credhub cert...
  #     -----END CERTIFICATE-----
  #     -----BEGIN CERTIFICATE-----
  #     ...UAA cert...
  #     -----END CERTIFICATE-----

  TERRAFORM_STATE_FILE_PATH: terraform.tfstate

  PREFIX: /concourse/main
  # - Optional
  FOUNDATION_PREFIX: ""
  # - Optional
  # naming rule is "$PREFIX/${FOUNDATION_PREFIX}_key...""
  
  SKIP_TLS_VALIDATION: false

run:
  path: platform-automation-pipelines/tasks/prepare-credhub-secrets-from-terraform-state.sh
