
s3:
  endpoint: https://s3.ap-northeast-2.amazonaws.com
  access_key_id: ((aws_access_key_id))
  secret_access_key: ((aws_secret_access_key))
  region_name: "ap-northeast-2"
  buckets:
    platform_automation: mkim-platform-automation
    pivnet_products: awstest-pivnet-products
    installation: awstest-installation
    bbr-backup: awstest-bbr-backup


git:
  platform_automation_pipelines:
    uri: git@github.com:myminseok/platform-automation-pipelines-template.git
    branch: master
  platform_automation_configs:
    uri: git@github.com:myminseok/platform-automation-pipelines-template.git
    #uri: git@github.com:myminseok/platform-automation-configuration-template.git
    branch: master
  user: 
    email: user@pivotal.io
    #username: ((git_user.username))
    username: "Platform Automation Bot"
  private_key: ((git_private_key.private_key))

credhub:
  server: https://credhub.pcfdemo.net:8844
  ca_cert: ((credhub_ca_cert.certificate))
  client: ((credhub_client.username))
  secret: ((credhub_client.password))
  interpolate_folders: dev/config dev/env dev/download-products

pivnet: 
  token: ((pivnet_token))

#vcenter:
#  datacenter: datacenter
#  insecure: 1
#  url: 10.10.10.10
#  username: ((vcenter_user.username))
#  password: ((vcenter_user.password))

