---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/rootfs

inputs:
- name: platform-pipelines
- name: env

run:
  path: platform-pipelines/tasks/pks/configure-pks-cli-user/task.sh

params:
  PKS_ENV_FILE: pks-env.yml
  ENV_FILE: env.yml

## reference: https://github.com/pivotalservices/concourse-pipeline-samples/tree/master/tasks/pcf/pks/configure-pks-cli-user
