products:
  opsman:
    product-version: "2.9.1"
    pivnet-product-slug: ops-manager
    pivnet-file-glob: "ops-manager-aws*.yml"
    download-stemcell: "false"
    pivnet-api-token: ((pivnet_token))

  tas:
    product-version: "2.9.1"
    pivnet-product-slug: elastic-runtime
    pivnet-file-glob: "cf*.pivotal"
    stemcell-iaas: aws
    pivnet-api-token: ((pivnet_token))
   
 
  healtheatch:
    product-version: "2.9.1"
    pivnet-product-slug: elastic-runtime
    pivnet-file-glob: "cf*.pivotal"
    stemcell-iaas: aws
    pivnet-api-token: ((pivnet_token))


